src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rabbit/RabbitMQListener.kt

DataService -> Dataset i metode-navn ein stad

Rename method to reflect domain of application

---

src/main/java/no/dcat/harvester/settings/RabbitMQSettings.java

Denne skal fikse eit issue rundt feilande handtering av "dataset.all.HarvestTrigger" melding. Gjelder kun gammal dataset-harvester, derfor merge kun til deploy/fdk-dataset-harvester

Modifiy topic subscription

---

pom.xml
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterActivity.kt

Har et håp om at dette hindrer den fra å knele i prod

chore: limit harvest threads

---

src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/DatasetHarvester.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvestHelpers.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/model/DBO.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/DatasetService.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/ZipService.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/DatasetServiceTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/TestData.kt

Ene modellen i prod passerte 16mb, sååå: gzip :tada:

fix: compress model before saving to mongodb

---

src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/DatasetHarvester.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvestHelpers.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterActivity.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/model/DBO.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rdf/RDFUtils.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/TestData.kt
src/test/resources/catalog_0_diff_update.ttl
src/test/resources/harvest_response_2_catalog_meta.ttl
src/test/resources/harvest_response_2_dataset_meta.ttl

modified har tydeligvis muliplisitet 1 til 1

fix: modified as last changed date

---

src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/controller/CatalogsController.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/controller/DatasetsController.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rdf/RDFUtils.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/contract/CatalogsContract.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/contract/DatasetsContract.kt

chore: support rdf-serializations TRIG, TRIX & N-QUADS

---

pom.xml
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/adapter/DatasetAdapter.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterActivity.kt

resolves https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/406

fix: add timeout for DatasetAdapter

---

pom.xml
src/main/resources/application.yml

chore: post micrometer metrics using statsd

---

pom.xml
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rabbit/RabbitMQPublisher.kt

resolve https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/447

new rabbit message

---

src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/adapter/HarvestAdminAdapter.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterActivity.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/model/HarvestAdmin.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rabbit/RabbitMQListener.kt
src/main/resources/application.yml
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/HarvestAdminAdapter.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/ContractMock.kt

chore: use new harvest-admin

---

src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/adapter/DatasetAdapter.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/DatasetHarvester.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterActivity.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/model/HarvestAdmin.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/model/HarvestReport.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/model/UpdateSearchMessage.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rabbit/RabbitMQPublisher.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rdf/RDFUtils.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/TestData.kt

resolves #107 
Eksempel på rapport som ble sendt ut i staging nå:
```
[
{
"id" = "8a706d0d-7ba6-4bf4-aa52-b88e5ac02725",
"url" = "https://registrering.staging.fellesdatakatalog.digdir.no/catalogs/555111290",
"dataType" = "dataset",
"harvestError" = false,
"timestamp" = 1648635227904,
"changedCatalogs" = [
{
"fdkId" = "05c13000-cd97-3551-a7da-a38d0372d000",
"uri" = "https://registrering.staging.fellesdatakatalog.digdir.no/catalogs/555111290"
}
],
"changedResources" = [
{
"fdkId" = "9e0c5ead-0559-3171-9ee7-81daa7fdc470",
"uri" = "https://registrering.staging.fellesdatakatalog.digdir.no/catalogs/555111290/datasets/95af09c0-f618-4924-aa69-e10ba7d399d5"
}
]
}
]
```

feat: harvest reports in harvest-completed message

---

src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/adapter/DatasetAdapter.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterActivity.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rdf/RDFUtils.kt

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/575

chore: rm unnecessary error logs

---

src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvestHelpers.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterActivity.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rdf/Namespace.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/UpdateService.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/UpdateServiceTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/TestData.kt
src/test/resources/catalog_with_series.ttl
src/test/resources/dataset_series.ttl
src/test/resources/harvest_response_4.ttl
src/test/resources/parsed_catalog_with_series.ttl
src/test/resources/parsed_dataset_series.ttl

feat: harvest dcat:DatasetSeries

---

docker-compose.yaml
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/DatasetHarvester.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterActivity.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/model/HarvestAdmin.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/model/RabbitHarvestTrigger.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rabbit/RabbitMQListener.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/HarvestAdminAdapter.kt

chore: add forceUpdate to incoming rabbit messages

---

pom.xml
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/Application.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/configuration/SecurityConfig.kt

https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/598

chore: replace deprecated security config

---

pom.xml
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvestHelpers.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/UpdateService.kt
src/main/resources/application.yml
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/UpdateServiceTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/ApiTestContext.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/DatabaseData.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/TestData.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/jwk/JwtToken.kt
src/test/resources/all_catalogs.ttl
src/test/resources/all_datasets.ttl
src/test/resources/all_metadata.ttl
src/test/resources/catalog_0.ttl
src/test/resources/catalog_0_diff_update.ttl
src/test/resources/catalog_1.ttl
src/test/resources/catalog_with_series.ttl
src/test/resources/dataset_0.ttl
src/test/resources/dataset_1.ttl
src/test/resources/dataset_series.ttl
src/test/resources/harvest_response_2_catalog_meta.ttl
src/test/resources/harvest_response_2_dataset_meta.ttl

add catalog triples to meta models

---

pom.xml
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterTest.kt

lagde issue på å oppgradere https://github.com/Informasjonsforvaltning/fdk-dataset-harvester/issues/195

chore: downgrade to jena4

---

.github/workflows/deploy-prod&demo.yaml
.github/workflows/deploy-staging.yaml
deploy/base/fdk-dataset-harvester-deployment.yaml
deploy/base/fdk-dataset-harvester-service.yaml
deploy/base/kustomization.yaml
deploy/demo/env.yaml
deploy/demo/kustomization.yaml
deploy/prod/env.yaml
deploy/prod/kustomization.yaml
deploy/staging/env.yaml
deploy/staging/kustomization.yaml

feat: add deploy with kustomize

---

pom.xml
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/DatasetHarvester.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterTest.kt

part of https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/932

fix: save datasets when republished with no changes

---

pom.xml
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/configuration/SecurityConfig.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/controller/DatasetsController.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/DatasetHarvester.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvestHelpers.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/repository/DatasetRepository.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/DatasetService.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/contract/DatasetsContract.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/contract/UpdateTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/DatasetServiceTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/TestUtils.kt

remove dataset

---

pom.xml
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/Application.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/controller/CatalogsController.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/controller/DatasetsController.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/DatasetHarvester.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/harvester/HarvesterActivity.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/model/DuplicateIRI.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rdf/RDFUtils.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/DatasetService.kt
src/main/resources/application.yml
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/contract/DatasetsContract.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/DatasetServiceTest.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/TestUtils.kt

feat: remove duplicates

---

src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/controller/DatasetsController.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/DatasetService.kt
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/service/TurtleService.kt
src/main/resources/application.yml
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/contract/DatasetsContract.kt
src/test/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/utils/DatabaseData.kt

feat: purge turtle files by fdkID

---

Dockerfile
deploy/demo/env.yaml
deploy/prod/env.yaml
deploy/staging/env.yaml
src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/configuration/SecurityConfig.kt
src/main/resources/application.yml

resolve https://github.com/Informasjonsforvaltning/fdk-team-private/issues/118

chore: cors config
